project:
  type: website
  output-dir: docs
  resources:
    - static

website:
  title: "craigmillard.com"
  site-url: https://craigmillard.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: archives.qmd
        text: Archives      
      - href: contact.qmd
        text: Contact / Bookings          

format:
  html:
    theme: zephyr
    page-layout: full
    toc: true
    toc-depth: 3

