project:
  type: website
  output-dir: docs
  resources:
    - static

website:
  title: "craigmillard.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: archives.qmd
        text: The Archives        

format:
  html:
    theme: flatly
    page-layout: full
    toc: true
    toc-depth: 3
    css: styles.css
