project:
  type: website
  output-dir: docs
  resources:
    - static

website:
  title: "craigmillard.com"
  site-url: https://craigmillard.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: arrangements.qmd
        text: Arrangements      
      - href: archives.qmd
        text: Archives      
      - href: contact.qmd
        text: Contact / Bookings    
  page-footer:
    left: "© 2025 Craig Millard"
    right:
      - icon: instagram
        href: https://www.instagram.com/pcraigmillard/
      - icon: facebook
        href: https://www.facebook.com/pcraigmillard
      - icon: youtube
        href: https://www.youtube.com/@pcraigmillard      

format:
  html:
    theme: zephyr
    page-layout: full
    toc: true
    toc-depth: 3
