---
title: "Books"
page-layout: full
---

In no particular order, here are some books I've read.

## Currently Reading

1. Dungeon Crawler Carl
2. Thinking, Fast and Slow

## From The Good Reads 100

1. To Kill a Mockingbird ★★★★★
2. 1984 ★★★★☆
3. Harry Potter and the Sorcerer's Stone (and the others) ★★★★☆
4. Lord of the Rings ★★★★★
5. The Hobbit ★★★★☆
6. Fahrenheit 451 ★★★★☆
7. Animal Farm ★★★★☆
8. The Catcher in The Rye ★★★☆☆
9. The Book Thief ★★★★☆
10. The Lion, The Witch, and the Wardrobe (and the others) ★★★★☆
11. The Lord of the Flies ★★★☆☆
12. A Wrinkle in Time ★★★★☆
13. Of Mice and Men ★★★★☆
14. Romeo and Juliet ★★★★☆
15. The Hitchhiker's Guide to the Galaxy ★★★★★
16. The Little Prince ★★★★☆
17. The Giver ★★★★☆
18. Where the Sidewalk Ends ★★★★☆
19. Wuthering Heights ★★★☆☆
20. Frankenstein ★★★★☆
21. The Bible (~1/3rd ish) ★★★☆☆
22. The Count of Monte Cristo ★★★★☆
23. A Tree Grows in Brooklyn ★★★★☆
24. The Stand ★★★★☆
25. Ender's Game (Ender and Shadow Series) ★★★★★
26. Watership Down ★★★★☆
27. A Game of Thrones (and the others) ★★★★☆
28. Life of Pi ★★★★☆
29. The Pillars of the Earth ★★★★☆
30. Charlie and the Chocolate Factory ★★★★☆
31. The Raven ★★★★☆
32. The Odyssey ★★★★☆
33. Crime and Punishment ★★★★☆
34. Slaughterhouse Five ★★★★☆
35. The Phantom Tollbooth ★★★★☆

## Speculative Fiction (Fantasy/Sci-Fi/Horror) Series

### By Brandon Sanderson
- Mistborn: The Final Empire ★★★★☆
- Mistborn: The Well of Ascension ★★★★☆
- Mistborn: The Hero of Ages ★★★★☆
- Mistborn: The Alloy of Law ★★★★☆
- Mistborn: The Bands of Mourning ★★★★☆
- Mistborn: Secret History ★★★★☆
- Stormlight: The Way of Kings ★★★★★
- Stormlight: Words of Radiance ★★★★★
- Stormlight: Oathbringer ★★★★☆
- Elantris ★★★★☆

### By Orson Scott Card
- Ender's Game ★★★★★
- Speaker for the Dead ★★★★☆
- Xenocide ★★★★☆
- Children of the Mind ★★★★☆
- Ender's Shadow ★★★★☆
- Shadow of the Hegemon ★★★★☆
- Shadow Puppets ★★★★☆
- Shadow of the Giant ★★★★☆
- Songmaster ★★★★☆

### By Joe Abercrombie
- The Blade Itself ★★★★☆
- Before They Are Hanged ★★★★☆
- Last Argument of Kings ★★★★☆
- Best Served Cold ★★★★☆

### By Brent Weeks
- The Way of Shadows ★★★★☆
- Shadow's Edge ★★★★☆
- Beyond the Shadows ★★★★☆
- The Black Prism ★★★★☆
- The Blinding Knife ★★★★☆
- The Broken Eye ★★★★☆
- The Blood Mirror ★★★★☆
- The Burning White ★★★★☆

### By Patrick Rothfuss
- The Name of the Wind ★★★★★
- The Wise Man's Fear ★★★★☆

### By Robin Hobb
- Assassin's Apprentice ★★★★☆
- Royal Assassin ★★★★☆
- Assassin's Quest ★★★★☆

### By Scott Lynch
- The Lies of Locke Lamora ★★★★☆
- Red Seas Under Red Skies ★★★★☆
- The Republic of Thieves ★★★★☆

### By Isaac Asimov
- Prelude to Foundation ★★★★☆
- Forward the Foundation ★★★★☆
- Foundation ★★★★☆
- Foundation and Empire ★★★★☆
- Second Foundation ★★★★☆
- Foundation's Edge ★★★★☆
- Foundation and Earth ★★★★☆
- Nightfall ★★★★☆

### By Stephen King
- Salem's Lot ★★★★☆
- The Shining ★★★★☆
- The Stand ★★★★☆
- Cujo ★★★★☆
- The Dark Tower: The Gunslinger ★★★★☆
- The Dark Tower II: The Drawing of the Three ★★★★☆
- The Dark Tower III: The Waste Lands ★★★★☆
- Insomnia ★★★★☆
- The Dark Tower IV: Wizard and Glass ★★★★☆
- The Dark Tower V: Wolves of the Calla ★★★★☆
- The Dark Tower VI: Song of Susannah ★★★★☆
- The Dark Tower VII: The Dark Tower ★★★★☆

### By Phillip Pullman
- The Golden Compass ★★★★☆
- The Subtle Knife ★★★★☆
- The Amber Spyglass ★★★★☆

### By Christopher Paolini
- Eragon ★★★★☆
- Eldest ★★★★☆
- Brisingr ★★★★☆
- Inheritance ★★★★☆

### Star Wars EU
- Lots, 20+ ★★★★☆

### By Stephenie Meyer
- Twilight ★★★☆☆
- New Moon ★★★☆☆
- Eclipse ★★★☆☆
- Breaking Dawn ★★★☆☆

### By Anne Rice
- Interview with the Vampire ★★★★☆

## Fiction

### By Chuck Palahniuk
- Fight Club ★★★★☆
- Survivor ★★★★☆
- Lullaby ★★★★☆
- Choke ★★★★☆

### By Dan Brown
- The Da Vinci Code ★★★★☆
- Angels and Demons ★★★★☆

### By Michael Connelly
- Bloodwork ★★★★☆
- The Poet ★★★★☆
- The Last Coyote ★★★★☆

### By Kevin J. Anderson
- Ill Wind ★★★★☆
- A lot of his Star Wars books (see above) ★★★★☆

### By John Grisham
- The Rainmaker ★★★★☆
- The Partner ★★★★☆
- The Street Lawyer ★★★★☆
- The Testament ★★★★☆
- The King of Torts ★★★★☆
- Playing for Pizza ★★★★☆
- The Summons ★★★★☆

### By Ayn Rand
- Atlas Shrugged ★★★★☆
- The Fountainhead ★★★★☆

### By Michael Crichton
- Congo ★★★★☆
- Sphere ★★★★☆

## Humor

### By David Sedaris
- For When You Are Engulfed in Flames ★★★★☆

### By Patrick McManus
- Never Sniff a Gift Fish ★★★★☆
- The Grasshopper Trap ★★★★☆
- Rubber Legs and White Tail-Hairs ★★★★☆

## Autobiographical

### By James Herriot
- All Creatures Great and Small ★★★★☆
- All Things Bright and Beautiful ★★★★☆
- All Things Wise and Wonderful ★★★★☆

## Other Authors and Genres (One-Offs, YA, Self-Help, Non-Fiction)

- Dune ★★★★☆
- The Martian ★★★★☆
- The Last Werewolf ★★★★☆
- Anathem ★★★★☆
- Prince of Thorns ★★★★☆
- Daring Greatly ★★★★☆
- This Naked Mind ★★★★☆
- How to Win Friends and Influence People ★★★★☆
- 48 Laws of Power ★★★★☆
- Power of One ★★★★☆
- Hullabaloo in the Guava Orchard ★★★★☆
- Redwall ★★★★☆
- Sick Puppy ★★★★☆
- Those Who Trespass ★★★★☆
- King Solomon's Mines ★★★★☆
- All Quiet on the Western Front ★★★★☆
- The Shadow of the Wind ★★★★☆
- The Outsiders ★★★★☆
- Inferno (The Divine Comedy) ★★★★☆
- A Brief History of Time ★★★★☆
- Chicken Soup for the Soul ★★★★☆
- The Sword of Truth ★★★★☆
- The BFG ★★★★☆
- The Screwtape Letters ★★★★☆
- The Ear, the Eye, and the Arm ★★★★☆
- The Island of Blue Dolphins ★★★★☆
- My Side of the Mountain ★★★★☆
- Julie and the Wolves ★★★★☆
- Dear Mr. Henshaw ★★★★☆
- Strider ★★★★☆
- The Mouse and the Motorcycle ★★★★☆
- Socks ★★★★☆
- Ramona ★★★★☆
- Ribsy ★★★★☆
- Super Fudge ★★★★☆
- Flowers for Algernon ★★★★☆
- Into the Wild ★★★★☆
- Shakespeare (Various) ★★★★☆
- The Canterbury Tales ★★★★☆
- Moby Dick ★★★★☆
- The Hound of the Baskervilles ★★★★☆
- The Jungle ★★★★☆
- The Strange Case of Dr. Jekyll and Mr. Hyde ★★★★☆
- Rosencrantz and Guildenstern are Dead ★★★★☆
- Robinson Crusoe ★★★★☆
- Guns, Germs and Steel ★★★★☆
- More Money Than God ★★★★☆
- The Lusty Argonian Maid ★★★★☆

---

*You can adjust the star ratings as you see fit!*